### ISSUE TITLE
"Seeds of Change" Shiny app

### ISSUE THREAD

**Issue by matthewkling** [BNHM/bnhm-shiny#2]
* **Title of your application**: Seeds of Change
* **Provide us with a brief abstract of the problem you are trying to solve**: This app is a decision support tool for ecological restoration projects in California, helping managers to select locations for seed collection and planting by analyzing spatial patterns of plant species distributions, climate, and soil characteristics.
* **Provide a description of how the code works and how you handle data**: In this Shiny application, raster data files are loaded from disk and processed according to user-defined inputs, calculating measures of environmental difference between a user's selected site and other locations across California. The results are displayed to the user via a leaflet map and a graph, and can also be downloaded by the user as a .tif file. 
* **Is your code available to the public?**: Yes. A beta version of the code can be viewed or cloned at https://github.com/matthewkling/seeds-of-change
* **List of R dependencies**: shiny, rintrojs, shinyalert, dplyr, tidyr, ggplot2, leaflet, raster, terra, grid, purrr, stringr

**Comment by mkoo** [comment]
Posted on the updated VM here:
https://bnhm-shiny.berkeley.edu/seeds-of-change

Read the news article: https://parks.berkeley.edu/news/2024/07/a-climate-change-tool-to-select-plant-seeds-for-resilience-in-california
